### ISSUE TITLE
Checkpoint sync for Besu

### ISSUE THREAD

**Issue by daniellehrner** [remyroy/ethstaker#20]
Hi! I am Daniel one of the developers of Hyperledger Besu. I and the rest of the team appreciate very much [the guide](https://github.com/remyroy/ethstaker/blob/main/merge-goerli-prater-alt.md) that you have written! Just one suggestion from us would be to change the [sync mode](https://besu.hyperledger.org/en/stable/Reference/CLI/CLI-Syntax/#sync-mode) for Besu.

We would recommend you to use the new [checkpoint sync](https://besu.hyperledger.org/en/stable/Concepts/Node-Types/#checkpoint-synchronization). It works the same as snap sync, but instead of syncing from genesis, it syncs from the block that contains the deployment of the deposit contract. Because of that it is much faster than snap sync. Rocketpool for example uses it as their default sync mode for Besu as well.

**Comment by remyroy** [comment]
Consider it done! I'll test it again and include that change in the guide. Thanks for your input!

**Comment by remyroy** [comment]
Completed with 79d67d5ff3a1ddcd1c9b722e259da4a4bb79d053
