### ISSUE TITLE
Outdated mev-boost setup instructions

### ISSUE THREAD

**Issue by TheAviationDoctor** [remyroy/ethstaker#34]
For Nimbus, [the guide](https://github.com/remyroy/ethstaker/blob/main/prepare-for-the-merge.md#configure-your-consensus-and-validator-client-to-use-mev-boost) currently says:

```
  --payload-builder=http://127.0.0.1:18550
```

which results in a Nimbus startup error.

The [Nimbus documentation](https://nimbus.guide/external-block-builder.html) indicates that the parameters should be:

```
  --payload-builder=true \
  --payload-builder-url=http://127.0.0.1:18550
```

**Comment by remyroy** [comment]
Updated with 0f6508986e300493e8c9d37e031e4262c1461e9f . Thanks for letting us know!
