### ISSUE TITLE
Extra metric request

### ISSUE THREAD

**Issue by CMTRACE** [remyroy/ethstaker#43]
Hi love the list. 

Perhaps it would be good to calculate a reliability score or apply pressure to teams to expose their own, with evidence.

Recent bad blocks, slow response times, unavailability and or Reddit/Twitter drama around MEV would be nice to know about when making an informed choice to support or not support a MEV team.

**Comment by remyroy** [comment]
I added some external monitoring websites yesterday that can help with that.
