### ISSUE TITLE
Make the JWT secret readable

### ISSUE THREAD

**Issue by egk10** [remyroy/ethstaker#7]
every time after rebooting , i must run  
sudo chmod +r /var/lib/goethereum/jwtsecret

**Comment by egk10** [comment]
on Kiln guide

**Comment by remyroy** [comment]
Let me try to find a nice solution for this.

**Comment by remyroy** [comment]
I just rebooted my machine and it seems like `/var/lib/goethereum/jwtsecret` was still readable for the lighthouse beacon node process to work properly. I'm not sure what would make that file unreadable after or during a reboot.
